#!/bin/sh
## This script executes the backup of the teamspeak-6-beta application folder and underlying files.
## For use in regular maintenance, data restore, and other DR exercises.
##
## Requires pigz.
##
## Process Explanation:  
##    tar -cpf /media/archive/ARCHIVE/bosnas_tsxserver/arkgameserver_YYYY-MM-DD.X.tar arkgameserver/
##

#set -x # to turn on verbose mode, useful for debugging

RUNDATE=$(date +%Y-%m-%d)
RUNTIME=$(date +%Y-%m-%d_%H%M)
SOURCEDIR=/app/ts6server-beta/teamspeak-server_linux_amd64     ## TO-DO: modify to non-hardcoded dir
TARG_DIR=/archive/level1/backups/ts6server-beta 
COUNT=$(ls ${TARG_DIR} | grep -c $(date +%Y-%m-%d'\.'))
VAR_NUM=$(ls ${TARG_DIR} | grep -cv '.gz\|.txt')
FILE_CNT=$((COUNT+1))
FILE_NAME=ts6server-beta_${RUNDATE}.${FILE_CNT}.tar
JOB_LOG=${SOURCEDIR}/logs/ts6server-beta_backup_${RUNTIME}.log

#################
fn_debug() {
##-- Used for testing
echo $(date +%Y-%m-%d" "%H:%M:%S)" | DEBUG | ===================================== "   >  ${JOB_LOG}
echo $(date +%Y-%m-%d" "%H:%M:%S)" | DEBUG | Run Date   = " "${RUNDATE}"               >> ${JOB_LOG}
echo $(date +%Y-%m-%d" "%H:%M:%S)" | DEBUG | Targ. Dir  = " "${TARG_DIR}"              >> ${JOB_LOG}
echo $(date +%Y-%m-%d" "%H:%M:%S)" | DEBUG | Targ File  = " "${TARG_DIR}/${FILE_NAME}" >> ${JOB_LOG}
echo $(date +%Y-%m-%d" "%H:%M:%S)" | DEBUG | Count      = " "${COUNT}"                 >> ${JOB_LOG}
echo $(date +%Y-%m-%d" "%H:%M:%S)" | DEBUG | Var Num    = " "${VAR_NUM}"               >> ${JOB_LOG}
echo $(date +%Y-%m-%d" "%H:%M:%S)" | DEBUG | File Count = " "${FILE_CNT}"              >> ${JOB_LOG}
echo $(date +%Y-%m-%d" "%H:%M:%S)" | DEBUG | File NAME  = " "${FILE_NAME}"             >> ${JOB_LOG}
echo $(date +%Y-%m-%d" "%H:%M:%S)" | DEBUG | ===================================== "   >> ${JOB_LOG}
##-- Used for testing
}
#################


#################
fn_findAndDelete() {
## Delete data & files older than x days                       ## TO-DO: modify to non-hardcoded day number
#set -x
find ${TARG_DIR} -mtime +9 -name '*.gz' -delete
find ${TARG_DIR} -mtime +9 -name '*.gz' -delete                >> ${JOB_LOG}

find ${TARG_DIR} -mtime +9 -name '*.txt' -delete
find ${TARG_DIR} -mtime +9 -name '*.txt' -delete               >> ${JOB_LOG}

find ${SOURCEDIR}/logs -mtime +9 -name '*.log' -delete
find ${SOURCEDIR}/logs -mtime +9 -name '*.log' -delete         >> ${JOB_LOG}

}
#################

#################
fn_backup() {
echo $(date +%Y-%m-%d" "%H:%M:%S)" | INFO | Backing up server... please wait..." 
echo $(date +%Y-%m-%d" "%H:%M:%S)" | INFO | Backing up server... please wait..."     >> ${JOB_LOG}

tar -cpf ${TARG_DIR}/"${FILE_NAME}" ${SOURCEDIR}

echo $(date +%Y-%m-%d" "%H:%M:%S)" | INFO | Backup complete & located at: ${TARG_DIR}/${FILE_NAME}" 
echo $(date +%Y-%m-%d" "%H:%M:%S)" | INFO | Backup complete & located at: ${TARG_DIR}/${FILE_NAME}"  >> ${JOB_LOG}
}

##################
fn_pigz (){
#set -x
if [ "$VAR_NUM" = 0 ] ;  then
        echo $(date +%Y-%m-%d" "%H:%M:%S)" | INFO | No Files to gzip, so skipping." 
        echo $(date +%Y-%m-%d" "%H:%M:%S)" | INFO | No Files to gzip, so skipping."    >> ${JOB_LOG}
        else 
    while [ "${VAR_NUM}" -gt 0 ] 
        do
        #GZIP_FILE=$(ls -t ${TARG_DIR}| grep -v gz | tail -n1 | awk '{print $1 }')
	GZIP_FILE=$(ls -t ${TARG_DIR}| grep tar | grep -v 'tar.gz' | tail -n50 | awk '{print $1 }')
	echo $(date +%Y-%m-%d" "%H:%M:%S)" | INFO | PIGZ operation started for file ${GZIP_FILE}" 
	echo $(date +%Y-%m-%d" "%H:%M:%S)" | INFO | PIGZ operation started for file ${GZIP_FILE}"   >> ${JOB_LOG}
## Comment out next line when debugging/testing and not want to actually perform the pigz operation
##        pigz -9 ${TARG_DIR}/"${GZIP_FILE}"
        echo $(date +%Y-%m-%d" "%H:%M:%S)" | INFO | PIGZ operation completed for file ${GZIP_FILE}" 
        echo $(date +%Y-%m-%d" "%H:%M:%S)" | INFO | PIGZ operation completed for file ${GZIP_FILE}" >> ${JOB_LOG}
        VAR_NUM=$((VAR_NUM-1))
        done
    echo $(date +%Y-%m-%d" "%H:%M:%S)" | INFO | PIGZ operation completed for all files in directory." 
    echo $(date +%Y-%m-%d" "%H:%M:%S)" | INFO | PIGZ operation completed for all files in directory." >> ${JOB_LOG}
fi
}
##################


##################
fn_outputDirSize () {
ARCHIVE_UTIL=$(ls -lh ${TARG_DIR} | head -n1 | awk '{print $2}')
echo $(date +%Y-%m-%d" "%H:%M:%S)" | INFO | Archive Size Dir written to temp file" 
echo $(date +%Y-%m-%d" "%H:%M:%S)" | INFO | Archive Size Dir written to temp file" >> ${JOB_LOG}
$(touch ${TARG_DIR}/${RUNTIME}_dir_size_is_${ARCHIVE_UTIL}.txt)
}
##################


fn_debug
fn_findAndDelete
fn_pigz
fn_backup
fn_outputDirSize


echo $(date +%Y-%m-%d" "%H:%M:%S)" | INFO | Process complete! Now exiting." 
echo $(date +%Y-%m-%d" "%H:%M:%S)" | INFO | Process complete! Now exiting."   >> ${JOB_LOG}

sleep 1
## End of script

